"""Init

Revision ID: b49edf807c71
Revises: 
Create Date: 2023-10-23 23:09:58.059039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49edf807c71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_humans_email'), 'humans', ['email'], unique=True)
    op.create_index(op.f('ix_humans_id'), 'humans', ['id'], unique=False)
    op.create_index(op.f('ix_humans_name'), 'humans', ['name'], unique=False)
    op.create_index(op.f('ix_humans_surname'), 'humans', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_humans_surname'), table_name='humans')
    op.drop_index(op.f('ix_humans_name'), table_name='humans')
    op.drop_index(op.f('ix_humans_id'), table_name='humans')
    op.drop_index(op.f('ix_humans_email'), table_name='humans')
    op.drop_table('humans')
    # ### end Alembic commands ###
